base_url = "https://do.lushisang.com"
title = "ğŸ˜¼å¹²é¥­çŒ«"
description = "å¹²é¥­çŒ«ï¼Œå¹²é¥­é­‚ï¼Œä¸è¦æ€‚ï¼Œå°±æ˜¯å¹²ï¼"
author = "Andy Lu"

default_language = "zh-cn"
# If used as theme, please uncomment this option
theme = "re137"
# To enable categories page
taxonomies = [{ name = "categories" }, { name = "tags" }]

[extra]

# Only user name is needed
github = "andyluss"
show_github_icon = true

# You can add your own items to list in the site navigator
re137_menu_links = [
    { url = "$BASE_URL", name = "ä¸»é¡µ" },
    { url = "$BASE_URL/categories", name = "åˆ†ç±»" }, # If enabled "taxonomies"
    { url = "$BASE_URL/tags", name = "æ ‡ç­¾" },       # If enabled "taxonomies"
    { url = "$BASE_URL/about", name = "å…³äº" },
]
